version: '3.7'
services:
  snapper:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - snapper_output:/snapper_output
    command: >
      --output_paths_format ${SNAPPER_FQDN_WITH_SCHEME}:8080{}
      --aws_bucket_name ${AWS_BUCKET_NAME}
    init: true
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  nginx:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - snapper_output:/usr/share/nginx/html/snapper_output

volumes:
    snapper_output:
