version: '3.7'
services:
  snapper:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - snapper_output:/snapper_output
    command: --output_paths_format "http://localhost:8080{}"
    init: true

  nginx:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - snapper_output:/usr/share/nginx/html/snapper_output

volumes:
    snapper_output:
