PATH: "/Users/revisor/Documents/Snapper/snapper"
IP: "127.0.0.1"
PORT: "8000"
USER_AGENT: "Mozilla/5.0 (Windows NT6.1) AppleWebKit/537.36 (KHTML,like Gecko) \
             Chrome/41.0.2228.0 Safari/537.36"